// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGoVAtegaPb5ti9jIPleC3FwjxyoBAHNc',
    appId: '1:676985016766:web:90da51f268dd18812ea9ef',
    messagingSenderId: '676985016766',
    projectId: 'track-zen',
    authDomain: 'track-zen.firebaseapp.com',
    storageBucket: 'track-zen.appspot.com',
    measurementId: 'G-7YDYEFN54N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaL2HhfWqrxccrfQ7U4Jck3gOuUSP_DfI',
    appId: '1:676985016766:android:cfe12fb3a0c2bffd2ea9ef',
    messagingSenderId: '676985016766',
    projectId: 'track-zen',
    storageBucket: 'track-zen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0KDBzheVJCJHn6IYn_VKzG9YxwfjjV0',
    appId: '1:676985016766:ios:f72eb9b7199032012ea9ef',
    messagingSenderId: '676985016766',
    projectId: 'track-zen',
    storageBucket: 'track-zen.appspot.com',
    iosBundleId: 'com.example.trackZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0KDBzheVJCJHn6IYn_VKzG9YxwfjjV0',
    appId: '1:676985016766:ios:f72eb9b7199032012ea9ef',
    messagingSenderId: '676985016766',
    projectId: 'track-zen',
    storageBucket: 'track-zen.appspot.com',
    iosBundleId: 'com.example.trackZen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGoVAtegaPb5ti9jIPleC3FwjxyoBAHNc',
    appId: '1:676985016766:web:0b5ea1965478c84e2ea9ef',
    messagingSenderId: '676985016766',
    projectId: 'track-zen',
    authDomain: 'track-zen.firebaseapp.com',
    storageBucket: 'track-zen.appspot.com',
    measurementId: 'G-JTYFYPWB86',
  );
}
